### ISSUE TITLE
Not working with 4.24.3

### ISSUE THREAD

**Issue by parthnaik92** [rfsheffer/QuestHands#6]
Thanks for the plugin! I am using Oculus branch 4.24.3 (https://github.com/Oculus-VR/UnrealEngine/tree/oculus-4.24.3-release-1.48.0-v16.0) and when I try to build the project, I get the following errors in `QuestHandFunctions.cpp`

Line 34:
```
return IOculusHMDModule::IsAvailable() && ovrp_GetInitialized();
<function-style-cast>': cannot convert from 'initializer list' to 'ovrp_GetInitialized
```

Line 66:
```
return OVRP_SUCCESS(ovrp_GetHandTrackingEnabled(&bResult)) && bResult;
<function-style-cast>': cannot convert from 'ovrpBool *' to 'ovrp_GetHandTrackingEnabled
```

Line 161:
```
if(OVRP_SUCCESS(ovrp_GetHandState(step, hand, &handState)))
<function-style-cast>': cannot convert from 'initializer list' to 'ovrp_GetHandState'
```

Line 291:
```
if(OVRP_SUCCESS(ovrp_GetSkeleton(hand, &skeleton)))
<function-style-cast>': cannot convert from 'initializer list' to 'ovrp_GetSkeleton'
```

Line 385:
```
return OVRP_SUCCESS(ovrp_SetVrApiPropertyInt(QuestHands::VRAPI_DYNAMIC_FOVEATION_ENABLED, enabled ? 1 : 0));
<function-style-cast>': cannot convert from 'initializer list' to 'ovrp_SetVrApiPropertyInt'
```

Can you please help?
Thanks!

**Comment by tstaufen** [comment]
Hey parthnaik,

I'm trying to get the Plugin running onn 4.25 and I'm experiencing similar issues (and more issues in other parts of the code).

I solved the issue you have by moving the #include of the "OVR_Plugin.h" to the top of the conditional include block (still inside the #if ...
See the attached Screenshot

![2020-05-06 18_03_19-Window](https://user-images.githubusercontent.com/6059008/81200254-ff217980-8fc3-11ea-9748-7451dc474c83.png)

**Comment by parthnaik92** [comment]
Thanks for the help, @tstaufen ! I tried your suggestion but now there are lots of errors being shown for OculusPluginWrapper.h. The errors for QuestHandFunctions are gone though.

**Comment by tstaufen** [comment]
Hey,
I've reached the same point as you now, after fixing all the things in the Plugin itself.
The OculusPluginWrapper.h throws weird errors. I have absolutely no idea how this is supposed to be fixed (see screenshot below).
How about your IOculusInputModule.h? The moment I create a fresh project and just go to that file I'm already getting errors there (non-working include statemenets).

Hopefully I will have time to try the tree "oculus-4.24.1-release-1.44.0-v12.0" later. I guess the plugin was developed on that version.

If you find any solution for the OculusPluginWrapper.h issues please let us know.
![2020-05-07 10_23_19-Window](https://user-images.githubusercontent.com/6059008/81272059-3c7e1980-904d-11ea-988a-6f6182656818.png)

**Comment by rfsheffer** [comment]
Hey guys. I'll take a look into this issue soon.

**Comment by parthnaik92** [comment]
@rfsheffer thank you!
@tstaufen if I find a solution, I will post it here

**Comment by rfsheffer** [comment]
the master branch now has a version of the plugin which supports Epics official 4.25 release. I will look into creating a release so people don't have to build code but for now, you still need a c++ code project to use this plugin. I will also create a branch for oculus's version 16 on their engine fork for unreal engine version 4.24.

**Comment by parthnaik92** [comment]
Thanks a lot!
